apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-quarkus-devfile-sample-ddng
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-quarkus-devfile-sample-ddng
    app.kubernetes.io/part-of: private-devfile
  name: private-quarkus-devfile-sample-ddng
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: private-quarkus-devfile-sample-ddng
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: private-quarkus-devfile-sample-ddng
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qzpx-tenant/private-devfile/private-quarkus-devfile-sample-ddng@sha256:b22253ecb2a526e5e9f5f893bd2ca9c42239f3886aa9d5a198e22c68a3709410
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
